theme: minima
title: First GitHub Page
author: enrichdev-en
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  First GitHub Page for learning and practice.

# social links
twitter_username: enrichdev
github_username:  enrichdev-en

show_excerpts: true # set to false to remove excerpts on the homepage
